// Decompiled with JetBrains decompiler
// Type: PlayUO.PHardwareInfo
// Assembly: Ultima.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6cc7e8bd89c5c6bf
// MVID: 0CAC2BC7-B53A-42C2-916C-A40DD9E7563D
// Assembly location: C:\Program Files (x86)\Electronic Arts\Ultima Online Classic\Ultima.Client.exe

namespace PlayUO
{
  internal class PHardwareInfo : Packet
  {
    public PHardwareInfo()
      : base((byte) 164, 149)
    {
      this.m_Stream.Write(new byte[148]
      {
        (byte) 3,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 24,
        (byte) 248,
        (byte) 18,
        (byte) 0,
        (byte) 130,
        (byte) 82,
        (byte) 251,
        (byte) 119,
        (byte) 8,
        (byte) 6,
        (byte) 19,
        (byte) 0,
        (byte) 69,
        (byte) 80,
        (byte) 251,
        (byte) 119,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 133,
        (byte) 243,
        (byte) 93,
        (byte) 1,
        (byte) 97,
        (byte) 1,
        (byte) 0,
        (byte) 80,
        (byte) 16,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 35,
        (byte) 1,
        (byte) 133,
        (byte) 243,
        (byte) 93,
        (byte) 1,
        (byte) 48,
        (byte) 150,
        (byte) 156,
        (byte) 47,
        (byte) 149,
        (byte) 43,
        (byte) 248,
        (byte) 119,
        (byte) 224,
        (byte) 136,
        (byte) 249,
        (byte) 119,
        byte.MaxValue,
        byte.MaxValue,
        byte.MaxValue,
        byte.MaxValue,
        (byte) 168,
        (byte) 249,
        (byte) 18,
        (byte) 0,
        (byte) 198,
        (byte) 107,
        (byte) 250,
        (byte) 119,
        (byte) 0,
        (byte) 0,
        (byte) 35,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 20,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 184,
        (byte) 2,
        (byte) 19,
        (byte) 0,
        (byte) 184,
        (byte) 2,
        (byte) 19,
        (byte) 0,
        (byte) 5,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 48,
        (byte) 87,
        (byte) 20,
        (byte) 0,
        (byte) 184,
        (byte) 2,
        (byte) 19,
        (byte) 0,
        (byte) 176,
        byte.MaxValue,
        (byte) 18,
        (byte) 0,
        (byte) 216,
        (byte) 249,
        (byte) 18,
        (byte) 0,
        (byte) 149,
        (byte) 43,
        (byte) 248,
        (byte) 119,
        (byte) 224,
        (byte) 1,
        byte.MaxValue,
        (byte) 149,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 44,
        (byte) 119,
        (byte) 250,
        (byte) 107,
        (byte) 198,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 0
      });
    }
  }
}
