// Decompiled with JetBrains decompiler
// Type: PlayUO.SpellID
// Assembly: Ultima.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6cc7e8bd89c5c6bf
// MVID: 0CAC2BC7-B53A-42C2-916C-A40DD9E7563D
// Assembly location: C:\Program Files (x86)\Electronic Arts\Ultima Online Classic\Ultima.Client.exe

namespace PlayUO
{
  public enum SpellID
  {
    None,
    Clumsy,
    CreateFood,
    Feeblemind,
    Heal,
    MagicArrow,
    NightSight,
    ReactiveArmor,
    Weaken,
    Agility,
    Cunning,
    Cure,
    Harm,
    MagicTrap,
    RemoveTrap,
    Protection,
    Strength,
    Bless,
    Fireball,
    MagicLock,
    Poison,
    Telekinesis,
    Teleport,
    Unlock,
    WallOfStone,
    ArchCure,
    ArchProtection,
    Curse,
    FireField,
    GreaterHeal,
    Lightning,
    ManaDrain,
    Recall,
    BladeSpirits,
    DispelField,
    Incognito,
    MagicReflect,
    MindBlast,
    Paralyze,
    PoisonField,
    SummonCreature,
    Dispel,
    EnergyBolt,
    Explosion,
    Invisibility,
    Mark,
    MassCurse,
    ParalyzeField,
    Reveal,
    ChainLightning,
    EnergyField,
    FlameStrike,
    GateTravel,
    ManaVampire,
    MassDispel,
    MeteorSwarm,
    Polymorph,
    Earthquake,
    EnergyVortex,
    Resurrection,
    AirElemental,
    SummonDaemon,
    EarthElemental,
    FireElemental,
    WaterElemental,
  }
}
